name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/todo
          tags: |
            type=sha,format=short,prefix=
      
      - name: Build and Push
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/todo:latest
          #cache-to: type=inline
          
      - name: Print Build Output
        run: |
          echo ${{ toJSON(steps.build.outputs.metadata) }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Print Tags
        run: |
          echo ${{ needs.build.outputs.tags }}
          echo $TAGS
        env:
          TAGS: ${{ needs.build.outputs.tags }}