name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/todoapp:latest
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/todoapp:latest
          cache-to: type=inline
          
      - name: Print Image ID
        run: |
          echo ${{ steps.build.outputs.imageid }}
          echo ${{ steps.build.outputs.metadata }}